models:
    container_name: models
    image: tp33/django
    volumes:
        - ./models/:/app
    ports:
        - "8001:8000"
    external_links:
        - mysql:db
    command: bash -c "python /app/manage.py makemigrations api; python /app/manage.py migrate; python /app/manage.py loaddata /app/data.json; mod_wsgi-express start-server --reload-on-change --working-directory /app /app/models/wsgi.py"
exp:
    container_name: exp
    image: tp33/django
    volumes:
        - ./exp/:/app
    ports:
        - "8002:8000"
    links:
        - models:models-api
        - kafka:kafka
        - es:es
    command: bash -c "python /app/manage.py migrate; mod_wsgi-express start-server --reload-on-change --working-directory /app /app/exp/wsgi.py"
web:
    container_name: web
    image: tp33/django
    volumes:
        - ./web/:/app
    ports:
        - "8000:8000"
    links:
        - exp:exp-api
    command: bash -c "python /app/manage.py migrate; mod_wsgi-express start-server --reload-on-change --working-directory /app /app/web/wsgi.py"

kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    hostname: kafka

es:
    image: elasticsearch:2.0
    container_name: es
    ports:
      - "9200:9200"

batch:
    image: tp33/django
    container_name: batch
    volumes:
       - ./:/app
    links:
       - kafka:kafka
       - es:es
    command: bash -c "python /app/batch_script.py"